[package]
authors = ["Damien Bataille <dbataille@nvidia.com>"]
title = "NVIDIA RTX Remix Commands Extension"
description = "This Extension create custom commands used by the NVIDIA RTX Remix Apps"
version = "1.0.2"
readme = "docs/README.md"
repository = "https://gitlab-master.nvidia.com/lightspeedrtx/lightspeed-kit/-/tree/master/source/extensions/lightspeed.trex.commands"
category = "internal"
keywords = [ "remix",]
changelog = "docs/CHANGELOG.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

[core]
# Load as early as possible
order = -100

[dependencies]
"omni.kit.commands" = {}
"omni.usd" = {}  # for usd

[[python.module]]
name = "lightspeed.trex.commands"
