[package]
version = "1.13.0"
authors =["Damien Bataille <dbataille@nvidia.com>"]
title = "NVIDIA RTX Remix Properties Pane Asset Replacements widget for the StageCraft"
description = "Asset Replacements Properties Pane widget for NVIDIA RTX Remix StageCraft App"
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
keywords = ["properties", "pane", "asset", "replacement", "widget"]
icon = "data/icon.png"
category = "internal"
preview_image = "data/preview.png"
repository = "https://gitlab-master.nvidia.com/lightspeedrtx/lightspeed-kit/-/tree/main/source/extensions/lightspeed.trex.properties_pane.shared.asset_replacements.widget"

[dependencies]
"lightspeed.layer_manager.core" = {}
"lightspeed.trex.material.core.shared" = {}
"lightspeed.trex.properties_pane.material.widget" = {}
"lightspeed.trex.properties_pane.mesh.widget" = {}
"lightspeed.trex.properties_pane.particle.widget" = {}
"lightspeed.trex.replacement.core.shared" = {}
"lightspeed.trex.selection_tree.widget" = {}
"lightspeed.trex.utils.common" = {}
"lightspeed.trex.utils.widget" = {}
"lightspeed.common" = {}
"omni.flux.bookmark_tree.model.usd" = {}
"omni.flux.bookmark_tree.widget" = {}
"omni.flux.selection_history_tree.widget" = {}
"omni.flux.selection_history_tree.model.usd" = {}
"omni.flux.layer_tree.usd.widget" = {}
"omni.flux.utils.common" = {}
"omni.flux.utils.widget" = {}
"omni.ui" = {}
"omni.usd" = {}
"omni.client" = {}
"omni.kit.menu.utils" = {}

[[python.module]]
name = "lightspeed.trex.properties_pane.widget"

[[test]]
dependencies = [
    "lightspeed.trex.tests.dependencies",
    "lightspeed.trex.contexts",
    "omni.kit.test_suite.helpers",
]

args = [
    "--/renderer/mdl/searchPaths/templates=${lightspeed.trex.app.resources}/deps/omni_core_materials/Base;${kit}/mdl/core/Base;${kit}/mdl/core/Volume;${kit}/mdl/core/mdl"
]

stdoutFailPatterns.exclude = [
    "*[omni.kit.registry.nucleus.utils.common] Skipping deletion of:*",
]

[[test]]
name = "startup"
dependencies = [
    "lightspeed.trex.tests.dependencies",
]
