[package]
# Semantic Versionning is used: https://semver.org/
version = "1.18.3"
# Lists people or organizations that are considered the "authors" of the package.
authors = ["Damien Bataille <dbataille@nvidia.com>"]

# The title and description fields are primarly for displaying extension info in UI
description = "Utility for Flux widgets"
title = "Flux widget utils"

# Path (relative to the root) or content of readme markdown file for UI.
readme = "docs/README.md"

# One of categories for UI.
category = "Widget"

# Keywords for the extension
keywords = ["kit", "flux", "utils", "widget"]

# Location of change log file in target (final) folder of extension, relative to the root.
# More info on writing changelog: https://keepachangelog.com/en/1.0.0/
changelog = "docs/CHANGELOG.md"

# Preview image and icon. Folder named "data" automatically goes in git lfs (see .gitattributes file).
# Preview image is shown in "Overview" of Extensions window. Screenshot of an extension might be a good preview image.
preview_image = "data/images/preview.png"

# Icon is shown in Extensions window, it is recommended to be square, of size 256x256.
icon = "data/images/icon.png"

[dependencies]
# omni.kit.pip_archive has Pillow and numpy. Adding Pillow in requirements will not work, because Pillow needs to
# import PIL, not import Pillow.
"omni.appwindow" = {}
"omni.client" = {}
"omni.flux.info_icon.widget" = {}
"omni.flux.utils.common" = {}
"omni.kit.pip_archive" = {}
"omni.kit.search_core" = {}
"omni.kit.widget.filebrowser" = {}
"omni.kit.widget.prompt" = {}
"omni.kit.widget.search_delegate" = {}  # Required to display search field in the file picker
"omni.kit.window.cursor" = {}
"omni.kit.window.filepicker" = {}
"omni.ui" = {}
"omni.usd" = {}

[[python.module]]
name = "omni.flux.utils.widget"

[[test]]
dependencies = [
    "omni.flux.tests.dependencies",
]

stdoutFailPatterns.exclude = [
    "*[omni.kit.registry.nucleus.utils.common] Skipping deletion of:*",
]
