[package]
version = "1.15.5"
authors = ["dbataille@nvidia.com"]
repository = "https://gitlab-master.nvidia.com/lightspeedrtx/lightspeed-kit"
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
keywords = ["remix", "app", "ressouces"]
title = "NVIDIA RTX Remix Resources"
description = "This Extension contains resources (images, icons) used by NVIDIA RTX Remix and splash screen."
icon = "data/icon.png"
category = "internal"
preview_image = "data/preview.png"

[core]
order = -1000
