[package]
version = "1.0.3"
authors = ["dbataille@nvidia.com"]
repository = "https://gitlab-master.nvidia.com/lightspeedrtx/lightspeed-kit"
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
keywords = ["remix", "viewport", "camera"]
title = "NVIDIA RTX Remix Viewports Menubar Camera implementation"
description = "Viewports Menubar Camera implementation for NVIDIA RTX Remix App"
icon = "data/icon.png"
category = "internal"
preview_image = "data/preview.png"

[dependencies]
"omni.flux.utils.common" = {}
"omni.kit.viewport.menubar.camera" = {}

[[python.module]]
name = "lightspeed.trex.viewports.menubar.camera"
