[package]
authors =["Pierre-Olivier Trottier <ptrottier@nvidia.com>"]
title = "NVIDIA RTX Remix Components Pane implementation for the IngestCraft"
description = "Components Pane implementation for NVIDIA RTX Remix IngestCraft App"
version = "1.0.3"
readme = "docs/README.md"
repository = "https://gitlab-master.nvidia.com/lightspeedrtx/lightspeed-kit/-/tree/main/source/extensions/lightspeed.trex.components_pane.ingestcraft.controller"
category = "internal"
keywords = [ "remix",]
changelog = "docs/CHANGELOG.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

[dependencies]
"lightspeed.trex.components_pane.ingestcraft.models" = {}
"omni.flux.tree_panel.widget" = {}
"omni.flux.utils.common" = {}

[[python.module]]
name = "lightspeed.trex.components_pane.ingestcraft.controller"
