[package]
authors =["Damien Bataille <dbataille@nvidia.com>"]
title = "NVIDIA RTX Remix shared layout"
description = "Shared layout for NVIDIA RTX Remix App"
version = "1.2.1"
readme = "docs/README.md"
repository = "https://gitlab-master.nvidia.com/lightspeedrtx/lightspeed-kit/-/tree/main/source/extensions/lightspeed.trex.layout.shared.base"
category = "internal"
keywords = [ "remix",]
changelog = "docs/CHANGELOG.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

[dependencies]
"lightspeed.trex.app.setup" = {}
"lightspeed.trex.contexts" = {}
"omni.flux.header_navigator.widget" = {}
"omni.flux.utils.common" = {}
"omni.ui" = {}

[python]
[[python.module]]
name = "lightspeed.trex.layout.shared.base"
