[package]
version = "2.0.0"
authors = ["dbataille@nvidia.com"]
repository = "https://gitlab-master.nvidia.com/lightspeedrtx/lightspeed-kit"
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
keywords = ["event", "save", "manager", "recent"]
title = "Lightspeed Event Save recent"
description = "Extension that update the recent saved file"
icon = "data/icon.png"
category = "internal"
preview_image = "data/preview.png"

[dependencies]
"lightspeed.events_manager" = {}
"lightspeed.layer_manager.core" = {}
"lightspeed.trex.recent_projects.core" = {}
"omni.flux.utils.common" = {}
"omni.client" = {}
"omni.usd" = {}

[[python.module]]
name = "lightspeed.event.save_recent"
