[package]
# Semantic Versionning is used: https://semver.org/
version = "1.4.3"

# Lists people or organizations that are considered the "authors" of the package.
authors = ["Damien Bataille <dbataille@nvidia.com>"]

# The title and description fields are primarly for displaying extension info in UI
description = "Content library widget to show any data, with a menu and metadata panel"
title = "Flux Content library widget"

# Path (relative to the root) or content of readme markdown file for UI.
readme = "docs/README.md"

# One of categories for UI.
category = "Widget"

# Keywords for the extension
keywords = ["kit", "flux", "content", "library", "widget"]

# Location of change log file in target (final) folder of extension, relative to the root.
# More info on writing changelog: https://keepachangelog.com/en/1.0.0/
changelog = "docs/CHANGELOG.md"

# Preview image and icon. Folder named "data" automatically goes in git lfs (see .gitattributes file).
# Preview image is shown in "Overview" of Extensions window. Screenshot of an extension might be a good preview image.
preview_image = "data/images/preview.png"

# Icon is shown in Extensions window, it is recommended to be square, of size 256x256.
icon = "data/images/icon.png"

[dependencies]
"omni.flux.content_viewer.widget" = {}
"omni.flux.content_library.property.widget" = {}
"omni.flux.utils.common" = {}
"omni.flux.utils.widget" = {}
"omni.ui" = {}

[[python.module]]
name = "omni.flux.content_library.widget"
