[package]
# Semantic Versionning is used: https://semver.org/
version = "2.6.2"

# Lists people or organizations that are considered the "authors" of the package.
authors = ["Pierre-Olivier Trottier <ptrottier@nvidia.com>"]

# The title and description fields are primarly for displaying extension info in UI
description = "A repository of USD widget plugins for the Remix stage manager"
title = "Remix Stage Manager USD Widget Plugins"

# Path (relative to the root) or content of readme markdown file for UI.
readme = "docs/README.md"

# One of categories for UI.
category = "internal"

# Keywords for the extension
keywords = ["remix", "stage", "manager", "plugin", "widget", "usd"]

# Location of change log file in target (final) folder of extension, relative to the root.
# More info on writing changelog: https://keepachangelog.com/en/1.0.0/
changelog = "docs/CHANGELOG.md"

# Preview image and icon. Folder named "data" automatically goes in git lfs (see .gitattributes file).
# Preview image is shown in "Overview" of Extensions window. Screenshot of an extension might be a good preview image.
preview_image = "data/images/preview.png"

# Icon is shown in Extensions window, it is recommended to be square, of size 256x256.
icon = "data/images/icon.png"

[dependencies]
"lightspeed.common" = {}
"lightspeed.layer_manager.core" = {}
"lightspeed.trex.asset_replacements.core.shared" = {}
"lightspeed.trex.commands" = {}  # Required for the Particle commands
"lightspeed.trex.logic.core" = {}
"lightspeed.trex.skeleton_replacements.widget" = {}
"lightspeed.trex.utils.common" = {}
"lightspeed.trex.viewports.shared.widget" = {}
"omni.flux.stage_manager.plugin.tree.usd" = {}
"omni.flux.stage_manager.plugin.widget.usd" = {}
"omni.flux.utils.common" = {}
"omni.flux.utils.widget" = {}
"omni.graph" = {}
"omni.kit.commands" = {}
"omni.ui" = {}
"omni.usd" = {}

[[python.module]]
name = "lightspeed.trex.stage_manager.plugin.widget.usd"

[[test]]
dependencies = [
    "lightspeed.trex.tests.dependencies",
    "lightspeed.trex.stage_manager.plugin.tree.usd",
    "omni.flux.stage_manager.factory",
]

stdoutFailPatterns.exclude = [
    "*[omni.kit.scene_view.opengl] No UsdRender.Product was found at '{render_product_path}'*",
    "*[omni.kit.registry.nucleus.utils.common] Skipping deletion of:*",
]

[[test]]
name = "startup"
dependencies = [
    "lightspeed.trex.tests.dependencies",
]
