[package]
version = "1.1.4"
authors =["Pierre-Olivier Trottier <ptrottier@nvidia.com>"]
title = "Mod Packaging Output Widget"
description = "Mod Packaging Output Widget implementation"
readme = "docs/README.md"
category = "internal"
keywords = ["kit", "lightspeed", "packaging", "output", "widget"]
changelog = "docs/CHANGELOG.md"
preview_image = "data/preview.png"
icon = "data/icon.png"
repository = "https://gitlab-master.nvidia.com/lightspeedrtx/lightspeed-kit/-/tree/main/source/extensions/lightspeed.trex.mod_packaging_output.widget"

[dependencies]
"lightspeed.common" = {}
"lightspeed.layer_manager.core" = {}
"lightspeed.trex.utils.widget" = {}
"omni.flux.utils.common" = {}
"omni.flux.utils.widget" = {}
"omni.ui" = {}
"omni.usd" = {}

[[python.module]]
name = "lightspeed.trex.mod_packaging_output.widget"

[[test]]
dependencies = [
    "lightspeed.trex.tests.dependencies",
]
