[package]
authors =["Damien Bataille <dbataille@nvidia.com>"]
title = "NVIDIA RTX Remix Components Pane implementation for the StageCraft"
description = "Components Pane implmentation for NVIDIA RTX Remix StageCraft App"
version = "1.0.3"
readme = "docs/README.md"
repository = "https://gitlab-master.nvidia.com/lightspeedrtx/lightspeed-kit/-/tree/master/source/extensions/lightspeed.trex.components_pane.stagecraft.controller"
category = "internal"
keywords = [ "remix",]
changelog = "docs/CHANGELOG.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

[dependencies]
"lightspeed.layer_manager.core" = {}
"lightspeed.trex.components_pane.stagecraft.models" = {}
"lightspeed.trex.utils.common" = {}
"omni.flux.tree_panel.widget" = {}
"omni.flux.utils.common" = {}
"omni.usd" = {}

[[python.module]]
name = "lightspeed.trex.components_pane.stagecraft.controller"
