[package]
version = "1.0.3"
authors = ["Nicolas Kendall-Bar <nkendallbar@nvidia.com>"]
title = "Particle System gizmos extension"
description = "Render particle system gizmos using omni.ui.scene"
readme = "docs/README.md"
repository = "https://gitlab-master.nvidia.com/lightspeedrtx/lightspeed-kit/-/tree/main/source/extensions/lightspeed.particle.gizmos"
category = "rendering"
keywords = ["ui", "scene", "docs", "documentation", "popover", "particle", "system", "gizmo", "omni.ui.scene", "manipulator"]
changelog = "docs/CHANGELOG.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

[dependencies]
"lightspeed.common" = {}
"lightspeed.trex.viewports.manipulators" = {}
"lightspeed.trex.schemas" = {}  # required for the particle schema HasAPI check
"lightspeed.trex.utils.common" = {}
"omni.kit.scene_view.opengl" = {}
"omni.kit.viewport.menubar.core" = {}
"omni.kit.viewport.menubar.display" = {}
"omni.ui.scene" = {}
"omni.usd" = {}

[[python.module]]
name = "lightspeed.particle.gizmos"

[settings.persistent.app.viewport.gizmo]
particlesGizmoVisible = true

[[test]]
# TODO: Verify if this is still needed after fixing golden tests.
args = [
    "--/app/window/dpiScaleOverride=1.0",
    "--/app/window/scaleToMonitor=false",
]

dependencies = [
    "lightspeed.trex.tests.dependencies",
    "omni.kit.viewport.utility",
]

stdoutFailPatterns.exclude = [
    "*[omni.kit.registry.nucleus.utils.common] Skipping deletion of:*",
]

[[test]]
name = "startup"
dependencies = [
    "lightspeed.trex.tests.dependencies",
]
