[package]
version = "0.2.1"
authors = ["ptrottier@nvidia.com"]
keywords = ["kit", "flux", "window", "popup", "dialog"]
title = "Omni Flux Dialogs"
description = "Simple but useful dialog window implementations"
category = "Widget"
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
icon = "data/icon.png"
preview_image = "data/preview.png"


[dependencies]
"omni.ui" = {}
"omni.flux.utils.common" = {}

[[python.module]]
name = "omni.flux.utils.dialog"
