[package]
version = "1.0.1"
authors = ["Pierre-Olivier Trottier <ptrottier@nvidia.com>"]
repository = "https://gitlab-master.nvidia.com/lightspeedrtx/lightspeed-kit"
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
keywords = ["event", "project", "validate", "mod"]
title = "Lightspeed Event Validate Project"
description = "Extension that validates the project structure whenever a stage is opened or saving"
icon = "data/icon.png"
category = "internal"
preview_image = "data/preview.png"

[dependencies]
"lightspeed.events_manager" = {}
"lightspeed.layer_manager" = {}
"omni.flux.utils.common" = {}
"omni.kit.commands" = {}
"omni.kit.notification_manager" = {}
"omni.kit.usd.layers" = {}
"omni.usd" = {}

[[python.module]]
name = "lightspeed.event.validate_project"
