[package]
# Semantic Versionning is used: https://semver.org/
version = "1.1.2"

# Lists people or organizations that are considered the "authors" of the package.
authors = ["Aleksei Rusev <arusev@nvidia.com>", "Pierre-Olivier Trottier <ptrottier@nvidia.com>"]

# The title and description fields are primarly for displaying extension info in UI
title = "PyCharm Debugger"
description = "PyCharm python debugger support."

# Path (relative to the root) or content of readme markdown file for UI.
readme = "docs/README.md"

# One of categories for UI.
category = "internal"

# Keywords for the extension
keywords = ["kit", "python", "debugger", "pycharm"]

# Location of change log file in target (final) folder of extension, relative to the root.
# More info on writing changelog: https://keepachangelog.com/en/1.0.0/
changelog = "docs/CHANGELOG.md"

# Preview image and icon. Folder named "data" automatically goes in git lfs (see .gitattributes file).
# Preview image is shown in "Overview" of Extensions window. Screenshot of an extension might be a good preview image.
preview_image = "data/images/preview.png"

# Icon is shown in Extensions window, it is recommended to be square, of size 256x256.
icon = "data/images/icon.png"

[dependencies]
"omni.flux.utils.common" = {}
"omni.kit.pipapi" = {}

[settings.exts."omni.flux.debug.pycharm"]
# Host and port for listen to debugger for
host = "127.0.0.1"
port = 33100
# PyCharm install location to find the pydevd Python module.
pycharm_location = ""
# The default behaviour is to install from pip instead of using PyCharm install
pip_install_pydevd = true
pydevd_version = "243.22562.23"
# If True, when this extension starts it'll connect to PyCharm and immediately suspend.
suspend_on_start = false

[[python.module]]
name = "omni.flux.debug.pycharm"

[[test]]
name = "startup"
# skip startup test, because a running pycharm debug server is required for startup
enabled = false

[[test]]
args = [
    "--/exts/omni.flux.debug.pycharm/pip_install_pydevd=0",
]

stdoutFailPatterns.exclude = [
    "*Could not setup pydevd module*",
    "*Failed to startup python extension*",
    "*[omni.kit.registry.nucleus.utils.common] Skipping deletion of:*",
]

dependencies = [
    "omni.flux.tests.dependencies",
]
