[package]
version = "1.2.1"
authors = ["Pierre-Olivier Trottier <ptrottier@nvidia.com>"]
title = "NVIDIA RTX Remix ComfyUI Widget"
description = "ComfyUI Widget for NVIDIA RTX Remix"
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
keywords = ["comfyui", "widget"]
icon = "data/icon.png"
category = "other"
preview_image = "data/preview.png"

[dependencies]
"lightspeed.trex.comfyui.core" = {}
"lightspeed.trex.contexts" = {}
"lightspeed.trex.utils.widget" = {}
"omni.flux.utils.common" = {}
"omni.flux.utils.widget" = {}
"omni.ui" = {}

[[python.module]]
name = "lightspeed.trex.comfyui.widget"

[[test]]
dependencies = [
    "lightspeed.trex.tests.dependencies",
    "omni.kit.test_suite.helpers",
]

stdoutFailPatterns.exclude = [
    # Generic Error
    "*[omni.kit.registry.nucleus.utils.common] Skipping deletion of:*",
]
