[package]
title = "Resources extension"
description = "This Extension contains resources (images, icons) used by the app and splash screen."
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
icon = "data/icon.png"
preview_image = "data/preview.png"
authors = [ "Damien Bataille <dbataille@nvidia.com>",]
version = "1.0.2"
repository = "https://gitlab-master.nvidia.com/lightspeedrtx/lightspeed-kit/-/tree/main/source/extensions/lightspeed_example.app.resources"
category = "example"
keywords = [ "remix",]
