[package]
authors =["Damien Bataille <dbataille@nvidia.com>"]
title = "NVIDIA RTX Remix Viewports Properties Pane implementation"
description = "Viewports Properties Pane implementation for NVIDIA RTX Remix App"
version = "1.1.3"
readme = "docs/README.md"
repository = "https://gitlab-master.nvidia.com/lightspeedrtx/lightspeed-kit/-/tree/main/source/extensions/lightspeed.trex.viewports.properties_pane.widget"
category = "internal"
keywords = [ "remix",]
changelog = "docs/CHANGELOG.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

[dependencies]
"lightspeed.trex.viewports.properties_pane.camera.widget" = {}
"lightspeed.trex.viewports.properties_pane.render.widget" = {}
"omni.flux.utils.common" = {}
"omni.ui" = {}


[[python.module]]
name = "lightspeed.trex.viewports.properties_pane.widget"
