[package]
version = "2.0.0"
authors = ["Shona Gillard <sgillard@nvidia.com>"]
repository = "https://gitlab-master.nvidia.com/lightspeedrtx/lightspeed-kit"
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
keywords = ["event", "waypoint"]
title = "Lightspeed Event Waypoint Creation"
description = "Extension that creates a waypoint for the game camera and manages other waypoints"
icon = "data/icon.png"
category = "internal"
preview_image = "data/preview.png"

[dependencies]
"lightspeed.trex.waypoint.core" = {}
"lightspeed.events_manager" = {}
"omni.usd" = {}
"omni.kit.usd.layers" = {}
"omni.kit.waypoint.core" = {}

[[python.module]]
name = "lightspeed.event.waypoint_creation"

[[test]]
dependencies = [
    "lightspeed.trex.capture.core.shared",
    "lightspeed.trex.tests.dependencies",
    "lightspeed.trex.viewports.shared.widget",  # grab the viewport because the viewport generate the persp camera
    "lightspeed.trex.viewports.stagecraft.bundle",  # grab the viewport because the viewport generate the persp camera
]

args = [
    # "--/renderer/mdl/searchPaths/templates=${kit}/../omni_core_materials/Base;${kit}/mdl/core/Base;${kit}/mdl/core/Volume;${kit}/mdl/core/mdl"
    # For what ever reason, using the command line directly will not resolve ${kit} for mdl path.
    # Need to use a .kit file
    "--merge-config=${app}/../../exts/lightspeed.trex.app.resources/data/tests/lightspeed.trex.app.resources.core_material.kit"
]

stdoutFailPatterns.exclude = [
    "*[omni.kit.scene_view.opengl] No UsdRender.Product was found at '{render_product_path}'*",
]
