[package]
version = "2.1.4"
authors =["Damien Bataille <dbataille@nvidia.com>"]
title = "NVIDIA RTX Remix Window for the IngestCraft"
description = "Window for NVIDIA RTX Remix IngestCraft App"
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
keywords = ["window", "ingestcraft", "ingest"]
icon = "data/icon.png"
category = "internal"
preview_image = "data/preview.png"
repository = "https://gitlab-master.nvidia.com/lightspeedrtx/lightspeed-kit"

[dependencies]
"lightspeed.common" = {}
"lightspeed.trex.contexts" = {}
"lightspeed.trex.layout.shared.mass_ingestion" = {}
"lightspeed.trex.sidebar" = {}
"lightspeed.trex.utils.widget" = {}

[[python.module]]
name = "lightspeed.trex.ingestcraft.widget"

[[test]]
dependencies = [
    "lightspeed.trex.tests.dependencies",
    "omni.flux.validator.plugin.check.usd",
    "omni.flux.validator.plugin.context.usd_stage",
    "omni.flux.validator.plugin.selector.usd",
    "omni.flux.validator.plugin.resultor.file"
]

args = [
    "--/renderer/mdl/searchPaths/templates=${lightspeed.trex.app.resources}/deps/omni_core_materials/Base;${kit}/mdl/core/Base;${kit}/mdl/core/Volume;${kit}/mdl/core/mdl"
]

stdoutFailPatterns.exclude = [
    "*[omni.kit.registry.nucleus.utils.common] Skipping deletion of:*",
]

[[test]]
name = "startup"
dependencies = [
    "lightspeed.trex.tests.dependencies",
    "omni.flux.validator.plugin.check.usd",
    "omni.flux.validator.plugin.context.usd_stage",
    "omni.flux.validator.plugin.selector.usd",
    "omni.flux.validator.plugin.resultor.file"
]

args = [
    "--/renderer/mdl/searchPaths/templates=${lightspeed.trex.app.resources}/deps/omni_core_materials/Base;${kit}/mdl/core/Base;${kit}/mdl/core/Volume;${kit}/mdl/core/mdl"
]

stdoutFailPatterns.exclude = [
    "*[omni.kit.registry.nucleus.utils.common] Skipping deletion of:*",
]
