[package]
# Semantic Versionning is used: https://semver.org/
version = "1.0.1"

# Lists people or organizations that are considered the "authors" of the package.
authors = ["Ed Leafe <eleafe@nvidia.com>"]

# The title and description fields are primarly for displaying extension info in UI
description = "Extension for managing Sentry data"
title = "Lightspeed Sentry Manager Core"

# Path (relative to the root) or content of readme markdown file for UI.
readme = "docs/README.md"

# One of categories for UI.
category = "internal"

# Keywords for the extension
keywords = ["lightspeed", "sentry", "manager", "core"]

# Location of change log file in target (final) folder of extension, relative to the root.
# More info on writing changelog: https://keepachangelog.com/en/1.0.0/
changelog = "docs/CHANGELOG.md"

# Preview image and icon. Folder named "data" automatically goes in git lfs (see .gitattributes file).
# Preview image is shown in "Overview" of Extensions window. Screenshot of an extension might be a good preview image.
preview_image = "data/images/preview.png"

# Icon is shown in Extensions window, it is recommended to be square, of size 256x256.
icon = "data/images/icon.png"

[dependencies]
"lightspeed.common" = {}
"lightspeed.trex.utils.common" = {}

[[python.module]]
name = "lightspeed.sentry_manager.core"

[[test]]
dependencies = [
    "lightspeed.trex.tests.dependencies",
]

stdoutFailPatterns.exclude = [
    "*[omni.kit.registry.nucleus.utils.common] Skipping deletion of:*",
]
