[package]
version = "1.1.0"
authors =["Damien Bataille <dbataille@nvidia.com>"]
title = "NVIDIA RTX Remix Material Core extension for the StageCraft"
description = "Extension that works on material data for NVIDIA RTX Remix StageCraft App"
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
keywords = ["material", "core"]
icon = "data/icon.png"
category = "internal"
preview_image = "data/preview.png"
repository = "https://gitlab-master.nvidia.com/lightspeedrtx/lightspeed-kit/-/tree/main/source/extensions/lightspeed.trex.material.core.shared"

[dependencies]
"omni.flux.utils.common" = {}
"omni.usd" = {}

[[python.module]]
name = "lightspeed.trex.material.core.shared"
