[package]
# Semantic Versionning is used: https://semver.org/
version = "1.3.2"

# Lists people or organizations that are considered the "authors" of the package.
authors = ["Pierre-Olivier Trottier <ptrottier@nvidia.com>"]

# The title and description fields are primarly for displaying extension info in UI
description = "A stage manager widget extension pulling all the required dependencies"
title = "Remix Stage Manager Widget"

# Path (relative to the root) or content of readme markdown file for UI.
readme = "docs/README.md"

# One of categories for UI.
category = "internal"

# Keywords for the extension
keywords = ["remix", "stage", "manager", "widget"]

# Location of change log file in target (final) folder of extension, relative to the root.
# More info on writing changelog: https://keepachangelog.com/en/1.0.0/
changelog = "docs/CHANGELOG.md"

# Preview image and icon. Folder named "data" automatically goes in git lfs (see .gitattributes file).
# Preview image is shown in "Overview" of Extensions window. Screenshot of an extension might be a good preview image.
preview_image = "data/images/preview.png"

# Icon is shown in Extensions window, it is recommended to be square, of size 256x256.
icon = "data/images/icon.png"

[dependencies]
"lightspeed.trex.stage_manager.plugin.filter.usd" = {}
"lightspeed.trex.stage_manager.plugin.interaction.usd" = {}
"lightspeed.trex.stage_manager.plugin.tree.usd" = {}
"lightspeed.trex.stage_manager.plugin.widget.usd" = {}
"lightspeed.trex.utils.widget" = {}
"omni.flux.stage_manager.plugin.column" = {}
"omni.flux.stage_manager.plugin.context.usd" = {}
"omni.flux.stage_manager.plugin.filter.usd" = {}
"omni.flux.stage_manager.plugin.interaction.usd" = {}
"omni.flux.stage_manager.plugin.listener.usd" = {}
"omni.flux.stage_manager.plugin.tree.usd" = {}
"omni.flux.stage_manager.plugin.widget.usd" = {}
"omni.flux.stage_manager.widget" = {}
"omni.ui" = {}

[settings.exts."omni.flux.stage_manager.core"]
schema = "${lightspeed.trex.app.resources}/data/stage_manager_schema/default_schema.json"

[[python.module]]
name = "lightspeed.trex.stage_manager.widget"

[[test]]
dependencies = [
    "lightspeed.trex.tests.dependencies",
    "lightspeed.trex.logic.core",
]

stdoutFailPatterns.exclude = [
    "*[omni.kit.registry.nucleus.utils.common] Skipping deletion of:*",
]

[[test]]
name = "startup"
dependencies = [
    "lightspeed.trex.tests.dependencies",
    "lightspeed.trex.logic.core",
]
