[package]
# Semantic Versionning is used: https://semver.org/
version = "0.1.5"

# Lists people or organizations that are considered the "authors" of the package.
authors = ["Alexander Jaus <ajaus@nvidia.com>"]

# The title and description fields are primarly for displaying extension info in UI
title = "Lightspeed Game Export Color Texture To Normal Map"
description="A menu that can invoke an color to normal texture converter on the textures in the loaded USD."

# Path (relative to the root) or content of readme markdown file for UI.
readme  = "docs/README.md"

# URL of the extension source repository.
repository="https://gitlab-master.nvidia.com/lightspeedrtx/lightspeed-kit/-/tree/main/source/extensions/lightspeed.color_to_normal.menu"

# One of categories for UI.
category = "internal"

# Keywords for the extension
keywords = ["kit", "color", "normal", "texture", "exporter","menu"]

# Location of change log file in target (final) folder of extension, relative to the root.
# More info on writing changelog: https://keepachangelog.com/en/1.0.0/
changelog="docs/CHANGELOG.md"

# Preview image and icon. Folder named "data" automatically goes in git lfs (see .gitattributes file).
# Preview image is shown in "Overview" of Extensions window. Screenshot of an extension might be a good preview image.
preview_image = "data/preview.png"

# Icon is shown in Extensions window, it is recommended to be square, of size 256x256.
icon = "data/icon.png"

[dependencies]
"omni.kit.menu.utils" = {}
"omni.kit.widget.layers" = {}
"lightspeed.layer_helpers" = {}
"lightspeed.layer_manager.core" = {}
"lightspeed.common" = {}
"lightspeed.color_to_normal.core" = {}
"lightspeed.error_popup.window" = {}
"lightspeed.progress_popup.window" = {}

# Main python module this extension provides, it will be publicly available as "import omni.example.hello".
[[python.module]]
name = "lightspeed.color_to_normal.menu"

[[test]]
dependencies = [
    "lightspeed.trex.tests.dependencies",
]

stdoutFailPatterns.exclude = [
    "*[omni.kit.registry.nucleus.utils.common] Skipping deletion of:*",
]
