[package]
version = "0.1.3"
authors = ["ajaus@nvidia.com"]
repository = "https://gitlab-master.nvidia.com/lightspeedrtx/lightspeed-kit"
keywords = ["lss", "lightspeed", "layer", "helper", "helpers"]
title = "LightSpeed Layer Helpers"
description = "Contains helper functions for lightspeed capture, export, and replacement layers."
category = "internal"
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
icon = "data/icon.png"
preview_image = "data/preview.png"

[dependencies]
"lightspeed.common" = {}
"lightspeed.layer_manager.core" = {}

[[python.module]]
name = "lightspeed.layer_helpers"
