[package]
version = "1.5.0"
authors =["Damien Bataille <dbataille@nvidia.com>"]
title = "NVIDIA RTX Remix widget utils"
description = "Utils helper for Lightspeed widgets"
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
keywords = ["trex", "utils", "widget"]
icon = "data/icon.png"
category = "internal"
preview_image = "data/preview.png"
repository = "https://gitlab-master.nvidia.com/lightspeedrtx/lightspeed-kit/-/tree/main/source/extensions/lightspeed.trex.utils.widget"

[dependencies]
"lightspeed.common" = {}
"lightspeed.trex.asset_replacements.core.shared" = {}
"lightspeed.trex.utils.common" = {}
"omni.ui" = {}
"omni.ui_query" = {}
"omni.usd" = {}
"omni.kit.widget.prompt" = {}
"omni.kit.menu.utils" = {}

[[python.module]]
name = "lightspeed.trex.utils.widget"

[[test]]
dependencies = [
    "lightspeed.trex.tests.dependencies",
    "omni.kit.test_suite.helpers",
]
