[package]
authors =["Pierre-Olivier Trottier <ptrottier@nvidia.com>"]
title = "NVIDIA RTX Remix Mod Packaging widget for the StageCraft"
description = "Mod Packaging widget for NVIDIA RTX Remix StageCraft App"
version = "1.4.0"
readme = "docs/README.md"
repository = "https://gitlab-master.nvidia.com/lightspeedrtx/lightspeed-kit/-/tree/main/source/extensions/lightspeed.trex.packaging.widget"
category = "internal"
keywords = [ "remix",]
changelog = "docs/CHANGELOG.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

[dependencies]
"omni.flux.utils.dialog" = {}
"lightspeed.layer_manager.core" = {}
"lightspeed.trex.mod_packaging_details.widget" = {}
"lightspeed.trex.mod_packaging_layers.widget" = {}
"lightspeed.trex.mod_packaging_output.widget" = {}
"lightspeed.trex.packaging.core" = {}
"lightspeed.trex.packaging.window" = {}
"lightspeed.trex.sidebar" = {}
"lightspeed.trex.utils.widget" = {}
"omni.appwindow" = {}
"omni.flux.utils.common" = {}
"omni.flux.utils.widget" = {}
"omni.kit.window.file" = {}
"omni.ui" = {}
"omni.usd" = {}

[[python.module]]
name = "lightspeed.trex.packaging.widget"

[[test]]
dependencies = [
    "lightspeed.trex.tests.dependencies",
    "omni.kit.test_suite.helpers",
]